name: Container Docker Image for main

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - 'main'

jobs:

  build:

    runs-on: ubuntu-latest 
    permissions:
      packages: write
      id-token: write
      contents: read
      actions: read
      security-events: write
    env:
      REGISTRY: ghcr.io
      GH_URL: https://github.com
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}
          flavor: |
            latest=true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build image and push to GitHub Container Registry
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file:  ./Dockerfile
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify cluster access
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Apply manifests
        run: |
          kubectl apply -f k8s-manifest/deployment.yaml -n wisecow --validate=false
          kubectl apply -f k8s-manifest/service.yaml -n wisecow --validate=false
          kubectl apply -f k8s-manifest/ingress.yaml -n wisecow --validate=false 
          kubectl -n wisecow set image deployment/wisecow wisecow=${{ env.REGISTRY }}/${{ github.repository }}:latest
          kubectl rollout status deployment/wisecow -n wisecow
          

  # deploy:
  #   name: Deploy to Kubernetes
  #   runs-on: self-hosted
  #   needs: build
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Install kubectl
  #       uses: azure/setup-kubectl@v3
  #       with:
  #         version: 'latest'

  #     - name: Restore kubeconfig
  #       run: |
  #         echo "$KUBECONFIG_B64" | base64 --decode > kubeconfig
  #         export KUBECONFIG=$(pwd)/kubeconfig
  #         kubectl version --client

  #     - name: Apply Kubernetes manifests
  #       run: |
  #         export KUBECONFIG=$(pwd)/kubeconfig
  #         kubectl apply -f k8s-manifest/deployment.yaml -n wisecow --validate=false
  #         kubectl apply -f k8s-manifest/service.yaml -n wisecow --validate=false
  #         kubectl apply -f k8s-manifest/ingress.yaml -n wisecow --validate=false 
         
  #     - name: Update Deployment with latest image
  #       run: |
  #         export KUBECONFIG=$(pwd)/kubeconfig
  #         kubectl -n wisecow set image deployment/wisecow wisecow=${{ env.REGISTRY }}/${{ github.repository }}:latest
